[phases.setup]
nixPkgs = ["ffmpeg", "python312"]

[phases.install]
cmds = [
  "python3.12 -m venv /app/.venv",
  "/app/.venv/bin/pip install --upgrade pip",
  "/app/.venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT"
